import httpx
from github import Github, GithubIntegration

from app.core.config import settings


def get_github_client(installation_id: int) -> Github:
    """
    Authenticate as a GitHub App installation and return a PyGithub client.

    Args:
        installation_id: The GitHub App installation ID from the webhook payload.

    Returns:
        An authenticated Github client scoped to that installation.
    """
    with open(settings.github_private_key_path, "r") as f:
        private_key = f.read()

    integration = GithubIntegration(
        integration_id=settings.github_app_id,
        private_key=private_key,
    )

    access_token = integration.get_access_token(installation_id).token
    return Github(access_token)


def get_pr_diff(github_client: Github, repo_full_name: str, pr_number: int) -> str:
    """
    Fetch the unified diff for a pull request.

    Args:
        github_client: An authenticated Github instance.
        repo_full_name: e.g. "octocat/Hello-World"
        pr_number: The PR number.

    Returns:
        The diff as a string.
    """
    repo = github_client.get_repo(repo_full_name)
    pr = repo.get_pull(pr_number)

    # PyGithub doesn't have a direct .diff property, so we use the raw API
    diff_url = pr.diff_url
    response = httpx.get(diff_url)
    return response.text


def post_review_comment(
    github_client: Github,
    repo_full_name: str,
    pr_number: int,
    file_path: str,
    line: int,
    body: str,
) -> None:
    """
    Post a review comment on a specific line of a PR.

    Args:
        github_client: An authenticated Github instance.
        repo_full_name: e.g. "octocat/Hello-World"
        pr_number: The PR number.
        file_path: The path to the file in the repo.
        line: The line number to comment on.
        body: The Markdown-formatted comment body.
    """
    repo = github_client.get_repo(repo_full_name)
    pr = repo.get_pull(pr_number)
    commit = pr.get_commits().reversed[0]

    pr.create_review_comment(
        body=body,
        commit=commit,
        path=file_path,
        line=line,
    )


def format_review_comment(
    function_name: str,
    complexity_score: int,
    suggestion_summary: str,
    refactored_code: str,
    explanation: str,
    priority: str,
    security_issues: list[str] | None = None,
) -> str:
    """
    Build a nicely formatted Markdown comment for the PR.

    Returns:
        A Markdown string ready to post.
    """
    severity_emoji = {"High": "🔴", "Medium": "🟡", "Low": "🟢"}.get(priority, "⚪")

    comment = f"""## {severity_emoji} geekPR — Code Review

**Function**: `{function_name}`
**Cyclomatic Complexity**: {complexity_score}
**Priority**: {priority}

### Summary
{suggestion_summary}

### Suggested Refactor
```python
{refactored_code}
```

### Why?
{explanation}
"""

    if security_issues:
        comment += "\n### ⚠️ Security Concerns\n"
        for issue in security_issues:
            comment += f"- {issue}\n"

    comment += "\n---\n*Generated by [geekPR](https://github.com/your-org/geekPR) — The Autonomous Reviewer*"
    return comment
