"""add llm_provider

Revision ID: 628236fca495
Revises: 8060cef7ded0
Create Date: 2026-03-25 09:44:51.454551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628236fca495'
down_revision: Union[str, Sequence[str], None] = '8060cef7ded0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_configs', sa.Column('llm_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_configs', 'llm_provider')
    # ### end Alembic commands ###
