"""initial tables

Revision ID: 8060cef7ded0
Revises: 
Create Date: 2026-03-25 08:54:07.716440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8060cef7ded0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('repo_full_name', sa.String(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_repo_full_name'), 'jobs', ['repo_full_name'], unique=False)
    op.create_table('repo_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=True),
    sa.Column('cc_threshold', sa.Integer(), nullable=True),
    sa.Column('bandit_enabled', sa.Boolean(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('auto_post', sa.Boolean(), nullable=True),
    sa.Column('exclude_patterns', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_configs_id'), 'repo_configs', ['id'], unique=False)
    op.create_index(op.f('ix_repo_configs_repo_full_name'), 'repo_configs', ['repo_full_name'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_title', sa.String(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_repo_full_name'), 'reviews', ['repo_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_repo_full_name'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_repo_configs_repo_full_name'), table_name='repo_configs')
    op.drop_index(op.f('ix_repo_configs_id'), table_name='repo_configs')
    op.drop_table('repo_configs')
    op.drop_index(op.f('ix_jobs_repo_full_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
